<?php


include_once '../model/Product.php';

class ProductController extends Product
{
    public function create($name, $description, $cat_id, $brd_id, $mrp, $base_price, $qyt, $unit, $loc, $status)
    {
        return $this->setProduct($name, $description, $cat_id, $brd_id, $mrp, $base_price, $qyt, $unit, $loc, $status);
    }

    public function update($id, $name, $des, $cat_id, $brd_id, $mrp, $base_price, $qyt, $unit, $loc)
    {
        return $this->updateProduct($id, $name, $des, $cat_id, $brd_id, $mrp, $base_price, $qyt, $unit, $loc);
    }

    public function get()
    {
        return $this->getAllProducts()->fetchAll();
    }

    public function inactiveProducts($check, $condition)
    {
        return $this->countElement($check, $condition); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        $status = 'Inactive';
        return parent::updateProductStatus($id, $status); // TODO: Change the autogenerated stub
    }

    public function reactive($id)
    {
        $status = 'Active';
        return parent::updateProductStatus($id, $status); // TODO: Change the autogenerated stub
    }

    public function getProductForUpdate($id)
    {
        $r = $this->getAllProducts();
        foreach ($r as $ar) {
            if ($ar['product_id'] == $id AND $ar['product_status'] == 'Active') {
                return $ar;
            }

        }
        return http_response_code(500);
    }

    public function productCount()
    {
        return $this->getAllProducts()->rowCount();
    }

    public function getPrductCart($name)
    {
        $qry = $this->getNameId($name);
        if ($qry->rowCount() > 0) {
            $r = $qry->fetchAll();
            $result = array();
            foreach ($r as $row) {
                if ($row['product_status'] == 'Active')
                   { $response = array("label" => $row['product_name'], "value" => $row['product_id'], "total_qyt" => $row['product_qyt'], "price" => $row['product_mrp']);
                array_push($result, $response);}
            }
            return $result;
        } else {
            $result = array('success' => 0, 'message' => 'failed');
            return $result;
        }
    }

    public function decrementQyt($id, $qyt){
        
        $ob=$this->countElement('product_id', $id);
        $r=$ob->fetch();
        return $this->updateProductQyt($id, ($r['product_qyt']-$qyt));
    }
    public function lowQytProducts(){



        return $this->inactive('product_qyt', '10')->rowCount();
    }

}